### ISSUE TITLE
Decide on room distribution

### ISSUE THREAD

**Issue by nickpodratz** [zehlendorf-wg/orga#3]
There are 6 rooms and we are 5 people, one room should be a shared one.
There is one room with a Wintergarden, which would be perfect to be shared. It also lies just next to the kitchen, so we could easily eat there together and stuff.
On the other hand there is also one connecting room which means that – to get to the room behind that one – one has to cross the connecting room. So having that as a shared room would make sense as well.
[grundriss.pdf](https://github.com/nickpodratz/wg-orga/files/1404132/grundriss.pdf)

**Comment by AlaidaHobbing** [comment]
I think that we should make the shared room the room with balcony. It is not the room with the wintergarden, but then all rooms are accessible from the floor then. And every room is private.

**Comment by nickpodratz** [comment]
Yes I was expecting this to happen as well. Still, let's wait till next week, not everyone has seen the flat yet.

**Comment by nickpodratz** [comment]
By talking, we found the following distribution:
Room 1: Nick
Room 2: Alaida
Room 3: David
Room 4: Fabian
Room 6: Miky
(The numbers refer to the annotated PDF file)
